
const date = new Date((Date.now() / 1000) + (10*60*60*24)).getTime();
const sampleDraws =  [
    {id: 1, winner: "Pilo Basualdo" ,title: "Matera Roja", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. \nEstamos probando la descripción al estilo lorem ipsum", brand: "De Mates", endDate: date, images: ["https://http2.mlstatic.com/matera-de-cuero-vacuno-D_NQ_NP_12938-MLA20069893007_032014-F.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 2, winner: "Julian Fenoglio" ,title: "Kit de Peluquería", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Peluca del pelado", endDate: date, images: ["https://mlstaticquic-a.akamaihd.net/vinilo-decorativo-de-pared-barberia-peluqueria-estilista-D_NQ_NP_607185-MLU31725182692_082019-F.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 3, winner: "Alan Taylor" ,title: "Zapatillas Nike Rn 2017", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Nike", endDate: date, images: ["https://c.static-nike.com/a/images/[t_PDP_1280_v1/f_auto/a8cbfzvkkvhrfv9pr23y/air-max-270-mens-shoe-jKGdGN.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 4, winner: "Nicolas Prezzavento" ,title: "2 Noches en el Delta", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Hotel del Delta", endDate: date, images: ["https://www.ahstatic.com/photos/3167_ho_00_p_2048x1536.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 5, winner: "Javier Ortega Desio" ,title: "Camastro King", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Colchones San Isidro", endDate: date, images: ["https://http2.mlstatic.com/camastro-king-size-sillon-reposera-reclinable-mod-dubai-ext-D_NQ_NP_690117-MLA31209070041_062019-F.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 6, winner: "Cintia Fernandez Toma" ,title: "Anteojos Aviator", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Óptica Alemana", endDate: date, images: ["https://i.linio.com/p/3636fa68a60b8087056733df51cd7175-product.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 7, winner: "Pilo Basualdo" ,title: "Matera Roja", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. \nEstamos probando la descripción al estilo lorem ipsum", brand: "De Mates", endDate: date, images: ["https://http2.mlstatic.com/matera-de-cuero-vacuno-D_NQ_NP_12938-MLA20069893007_032014-F.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 8, winner: "Julian Fenoglio" ,title: "Kit de Peluquería", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Peluca del pelado", endDate: date, images: ["https://mlstaticquic-a.akamaihd.net/vinilo-decorativo-de-pared-barberia-peluqueria-estilista-D_NQ_NP_607185-MLU31725182692_082019-F.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 9, winner: "Alan Taylor" ,title: "Zapatillas Nike Rn 2017", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Nike", endDate: date, images: ["https://c.static-nike.com/a/images/[t_PDP_1280_v1/f_auto/a8cbfzvkkvhrfv9pr23y/air-max-270-mens-shoe-jKGdGN.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 10, winner: "Nicolas Prezzavento" ,title: "2 Noches en el Delta", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Hotel del Delta", endDate: date, images: ["https://www.ahstatic.com/photos/3167_ho_00_p_2048x1536.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 11, winner: "Javier Ortega Desio" ,title: "Camastro King", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Colchones San Isidro", endDate: date, images: ["https://http2.mlstatic.com/camastro-king-size-sillon-reposera-reclinable-mod-dubai-ext-D_NQ_NP_690117-MLA31209070041_062019-F.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 12, winner: "Cintia Fernandez Toma" ,title: "Anteojos Aviator", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Óptica Alemana", endDate: date, images: ["https://i.linio.com/p/3636fa68a60b8087056733df51cd7175-product.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 13, winner: "Pilo Basualdo" ,title: "Matera Roja", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. \nEstamos probando la descripción al estilo lorem ipsum", brand: "De Mates", endDate: date, images: ["https://http2.mlstatic.com/matera-de-cuero-vacuno-D_NQ_NP_12938-MLA20069893007_032014-F.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 14, winner: "Julian Fenoglio" ,title: "Kit de Peluquería", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Peluca del pelado", endDate: date, images: ["https://mlstaticquic-a.akamaihd.net/vinilo-decorativo-de-pared-barberia-peluqueria-estilista-D_NQ_NP_607185-MLU31725182692_082019-F.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 15, winner: "Alan Taylor" ,title: "Zapatillas Nike Rn 2017", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Nike", endDate: date, images: ["https://c.static-nike.com/a/images/[t_PDP_1280_v1/f_auto/a8cbfzvkkvhrfv9pr23y/air-max-270-mens-shoe-jKGdGN.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 16, winner: "Nicolas Prezzavento" ,title: "2 Noches en el Delta", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Hotel del Delta", endDate: date, images: ["https://www.ahstatic.com/photos/3167_ho_00_p_2048x1536.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 17, winner: "Javier Ortega Desio" ,title: "Camastro King", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Colchones San Isidro", endDate: date, images: ["https://http2.mlstatic.com/camastro-king-size-sillon-reposera-reclinable-mod-dubai-ext-D_NQ_NP_690117-MLA31209070041_062019-F.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
    {id: 18, winner: "Cintia Fernandez Toma" ,title: "Anteojos Aviator", description: "Este artefacto cuenta con un palo de color azul y además cabra muy cheta. Estamos probando la descripción al estilo lorem ipsum", brand: "Óptica Alemana", endDate: date, images: ["https://i.linio.com/p/3636fa68a60b8087056733df51cd7175-product.jpg","https://cdn.webshopapp.com/shops/263001/files/287759514/image.jpg", "https://dafitistaticar-a.akamaihd.net/p/ay-not-dead-6921-052142-1-product.jpg"]},
];

const getDraw = (id) => {
    return sampleDraws[id%sampleDraws.length]
};

const participate = (userId, drawId) => {
    return true;
};

const stopParticipating = (userId, drawId) => {
    return true;
};

module.exports = {
    getDraw,
    participate,
    stopParticipating
};